// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yamal.DataAccess;

#nullable disable

namespace Yamal.DataAccess.Migrations
{
    [DbContext(typeof(YamalDbContext))]
    [Migration("20260908080038_DataBaseStruct")]
    partial class DataBaseStruct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Yamal.DataAccess.Entites.CarrierTypeLogosEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarrierTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("carrier_type_id");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_recommended");

                    b.Property<int>("LogoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("logo_id");

                    b.HasKey("Id");

                    b.HasIndex("CarrierTypeId");

                    b.HasIndex("LogoId");

                    b.ToTable("CarrierTypeLogos", (string)null);
                });

            modelBuilder.Entity("Yamal.DataAccess.Entites.LogoLibraryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("LogoLibrary");
                });

            modelBuilder.Entity("Yamal.DataAccess.Entites.MaterialsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<int>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_type");

                    b.Property<bool>("IsDownloadable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_downloadable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("preview_url");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Yamal.DataAccess.Entites.MediaCategoriesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("MediaCategories");
                });

            modelBuilder.Entity("Yamal.DataAccess.Entites.MediaTypesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("ColorSchemesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("color_schemes_json");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersSchema")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("parameters_schema");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("TemplatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("templates_json");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MediaTypes");
                });

            modelBuilder.Entity("Yamal.DataAccess.Entites.QuestionsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_email");

                    b.Property<int?>("UserEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.Property<string>("UserQuestion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_question");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Yamal.DataAccess.Entites.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Yamal.DataAccess.Entites.CarrierTypeLogosEntity", b =>
                {
                    b.HasOne("Yamal.DataAccess.Entites.MediaTypesEntity", "MediaType")
                        .WithMany("CarrierTypes")
                        .HasForeignKey("CarrierTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yamal.DataAccess.Entites.LogoLibraryEntity", "LogoLibrary")
                        .WithMany("CarrierTypeLogos")
                        .HasForeignKey("LogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogoLibrary");

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("Yamal.DataAccess.Entites.MediaTypesEntity", b =>
                {
                    b.HasOne("Yamal.DataAccess.Entites.MediaCategoriesEntity", "Category")
                        .WithMany("Types")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Yamal.DataAccess.Entites.QuestionsEntity", b =>
                {
                    b.HasOne("Yamal.DataAccess.Entites.UserEntity", null)
                        .WithMany("Questions")
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("Yamal.DataAccess.Entites.LogoLibraryEntity", b =>
                {
                    b.Navigation("CarrierTypeLogos");
                });

            modelBuilder.Entity("Yamal.DataAccess.Entites.MediaCategoriesEntity", b =>
                {
                    b.Navigation("Types");
                });

            modelBuilder.Entity("Yamal.DataAccess.Entites.MediaTypesEntity", b =>
                {
                    b.Navigation("CarrierTypes");
                });

            modelBuilder.Entity("Yamal.DataAccess.Entites.UserEntity", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
