version: "3.8"

services:
  backend:
    build:
      context: ./branding-calculator-backend
      dockerfile: Dockerfile
    container_name: branding-backend
    user: root
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/yamal.db;Foreign Keys=True;Mode=ReadWrite
    volumes:
      - ./yamal.db:/app/yamal.db
      - ./uploads:/app/uploads
    ports:
      - "5001:8080"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./branding-calculator-frontend
      dockerfile: Dockerfile
    container_name: branding-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
