version: '3.8'

services:
  backend:
    build:
      context: ./branding-calculator-backend
      dockerfile: Dockerfile
    container_name: branding-backend
    user: root
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
<<<<<<< HEAD
      - ASPNETCORE_URLS=http://0.0.0.0:5001
      - ConnectionStrings__DefaultConnection=Data Source=/app/Data/yamal.db;Foreign Keys=True;Mode=ReadWrite
=======
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/yamal.db;Foreign Keys=True;Mode=ReadWrite
>>>>>>> refs/remotes/origin/main
    volumes:
      - ./yamal.db:/app/yamal.db  # Монтируем ФАЙЛ
      - ./uploads:/app/uploads
    ports:
<<<<<<< HEAD
      - "5001:5001" 
=======
      - "5001:8080"
>>>>>>> refs/remotes/origin/main
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./branding-calculator-frontend
      dockerfile: Dockerfile
    container_name: branding-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
