server {
    listen 80;
    server_name _; # Принимаем любые запросы, так как они уже прошли через хостовой Nginx

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Обслуживание Angular (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }
}